### PR TITLE
new table

### PR DESCRIPTION
**Pull request by vzinche**

### CODE REVIEW

**Comment by constantinpape** [comment]
@vzinche what did change?

**Comment by vzinche** [comment]
Added a new table that David just asked for to the version 1.0.0

**Comment by constantinpape** [comment]
Ah ok, I thought you modified the existing table, sorry didn't parse the diff properly.

**Comment by vzinche** [comment]
I even called the pull request 'new table' :D

**Comment by constantinpape** [comment]
> I even called the pull request 'new table' :D

^^

I guess I am too used to just parsing diffs and if the diff is just something in a table I just skip it :D.

**Pull request merged**
