### PR TITLE
Start transition to new mobie layout

### PR DESCRIPTION
**Pull request by constantinpape**
- [x] `datasets.json` instead of `versions.json`
- [x] update all `images.json`
- [x] make bookmark folder with `default.json`; update and move `bookmarks.json`
- [x] add `misc/leveling.json`
- [x] remove `additional_tables.txt`
- [x] add the `AuthenticationMode:Anonymous` field to the xml

cc @tischi

### CODE REVIEW

**Comment by constantinpape** [comment]
Fixes #53

**Comment by constantinpape** [comment]
@tischi I added the `Authentication` field now:
https://github.com/platybrowser/platybrowser/blob/mobie/data/1.0.1/images/remote/sbem-6dpf-1-whole-raw.xml#L33

**Comment by constantinpape** [comment]
@tischi I think I have updated everything to the new mobie layout.
Let me know if something is incorrect or still missing.

**Comment by tischi** [comment]
I will test later today. This morning I am in Lab meetings....

**Pull request merged**
