### PR TITLE
Add example script for how to add an image

### PR DESCRIPTION
**Pull request by tischi**
@constantinpape 

I have not dared to run it yet not to fuck something up; does that look ok enough to give it a try?

### CODE REVIEW

**Comment by tischi** [comment]
I mean the add_image.py ?
I will .gitignore the other stuff.

**Review by constantinpape — COMMENTED** [review]
Looks good overall, and you can give it a try. See my comment about how to add single tifs.

**Comment by tischi** [comment]
@constantinpape 

it hangs inside `mobie.add_image(...)`

when I force quit I am getting this:

```
Traceback (most recent call last):
  File "/Users/tischer/Documents/platybrowser-project/misc/add_image.py", line 35, in <module>
    mobie.add_image(
  File "/Users/tischer/Documents/mobie-utils-python/mobie/image_data.py", line 218, in add_image
    view = utils.require_dataset_and_view(root, dataset_name, file_format,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tischer/Documents/mobie-utils-python/mobie/utils.py", line 94, in require_dataset_and_view
    validate_view_metadata(view, sources=[source_name])
  File "/Users/tischer/Documents/mobie-utils-python/mobie/validation/metadata.py", line 263, in validate_view_metadata
    validate_with_schema(view, "view")
  File "/Users/tischer/Documents/mobie-utils-python/mobie/validation/utils.py", line 45, in validate_with_schema
    if not _download_schema():
           ^^^^^^^^^^^^^^^^^^
  File "/Users/tischer/Documents/mobie-utils-python/mobie/validation/utils.py", line 36, in _download_schema
    if not _download(url, out_file):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tischer/Documents/mobie-utils-python/mobie/validation/utils.py", line 27, in _download
    r = requests.get(address)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tischer/mambaforge/envs/mobie/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tischer/mambaforge/envs/mobie/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tischer/mambaforge/envs/mobie/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tischer/mambaforge/envs/mobie/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tischer/mambaforge/envs/mobie/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/tischer/mambaforge/envs/mobie/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/tischer/mambaforge/envs/mobie/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/Users/tischer/mambaforge/envs/mobie/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/Users/tischer/mambaforge/envs/mobie/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/Users/tischer/mambaforge/envs/mobie/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tischer/mambaforge/envs/mobie/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

It seems it wants to connect to the internet? why?

**Comment by constantinpape** [comment]
> It seems it wants to connect to the internet? To download the schema...

Yes.

> Can this take a long time?

No. You're probably inside EMBL VPN that blocks the required port. Try outside of EMBL VPN.

**Comment by tischi** [comment]
@constantinpape I am outside, I am at home.

**Comment by tischi** [comment]
Inside EMBL it works.

**Comment by tischi** [comment]
@constantinpape 

now I am getting this:

```
===== Luigi Execution Summary =====

Scheduled 5 tasks of which:
* 1 complete ones were encountered:
    - 1 DummyTask()
* 1 failed:
    - 1 CopyVolumeLocal(...)
* 3 were left pending, among these:
    * 3 had failed dependencies:
        - 1 DownscalingLocal(...)
        - 1 DownscalingWorkflow(...)
        - 1 WriteDownscalingMetadata(...)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

Traceback (most recent call last):
  File "/Users/tischer/Documents/platybrowser-project/misc/add_image.py", line 35, in <module>
    mobie.add_image(
  File "/Users/tischer/Documents/mobie-utils-python/mobie/image_data.py", line 237, in add_image
    import_image_data(input_path, input_key, data_path,
  File "/Users/tischer/Documents/mobie-utils-python/mobie/import_data/image.py", line 35, in import_image_data
    downscale(in_path, in_key, out_path,
  File "/Users/tischer/Documents/mobie-utils-python/mobie/import_data/utils.py", line 105, in downscale
    raise RuntimeError("Downscaling failed")
RuntimeError: Downscaling failed
```

This is with:

- `file_format="ome.zarr"`
- `scale_factors=1 * [[2, 2, 2]]`

**Comment by tischi** [comment]
Sent in mattermost.

**Pull request closed without merging**
